"""update

Revision ID: e257b2eb0704
Revises: 3d53cc6bd546
Create Date: 2026-07-10 11:12:18.949552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e257b2eb0704'
down_revision: Union[str, None] = '3d53cc6bd546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_items', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('plan_items', sa.Column('score_components', sa.JSON(), nullable=True))
    op.add_column('plan_runs', sa.Column('date_scope', sa.String(length=20), nullable=True))
    op.add_column('plan_runs', sa.Column('intent_json', sa.JSON(), nullable=True))
    op.add_column('plan_runs', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('plan_runs', sa.Column('client_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_runs', 'client_context')
    op.drop_column('plan_runs', 'stage')
    op.drop_column('plan_runs', 'intent_json')
    op.drop_column('plan_runs', 'date_scope')
    op.drop_column('plan_items', 'score_components')
    op.drop_column('plan_items', 'score')
    # ### end Alembic commands ###
